apiVersion: v1
kind: Secret
metadata:
  name: cluster-placeholder-install-config
  namespace: cluster-placeholder
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: openshiftpartnerlabs.com
    metadata:
      name: cluster-placeholder
    controlPlane:
      name: master
      platform:
        gcp:
          type: n2-standard-8
          zones:
            - us-central1-a
            - us-central1-b
            - us-central1-c
      replicas: 3
    compute:
      - name: worker
        platform:
          gcp:
            rootVolume:
              size: 128
              type: pd-ssd
            type: n2-standard-8
            zones:
              - us-central1-a
              - us-central1-b
              - us-central1-c
        replicas: 3
    networking:
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
      networkType: OVNKubernetes
    platform:
      gcp:
        region: us-central1
    publish: External
