apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  name: cluster-placeholder-ocp-installer
  namespace: cluster-placeholder
spec:
  forProvider:
    tags:
      Purpose: OpenShift-Installer
      CreatedBy: Crossplane
      Product: OpenShift
  providerConfigRef:
    name: default
