apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: cluster-placeholder-worker
  namespace: cluster-placeholder
spec:
  clusterDeploymentRef:
    name: cluster-placeholder
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: 128
        diskType: Premium_LRS
      type: Standard_D8s_v5
      zones:
        - "1"
        - "2"
        - "3"
  replicas: 3
  labels:
    node-role.kubernetes.io/worker: ""
