apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: FederatedIdentityCredential
metadata:
  name: cluster-placeholder-federated-cred
  namespace: cluster-placeholder
spec:
  forProvider:
    resourceGroupNameRef:
      name: cluster-placeholder
    identityRef:
      name: cluster-placeholder-ocp-installer
    issuer: https://token.actions.githubusercontent.com
    subject: system:serviceaccount:cluster-placeholder:installer
    audiences:
      - api://AzureADTokenExchange
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: azure-credentials-raw
    namespace: cluster-placeholder
