apiVersion: v1
kind: Secret
metadata:
  name: cluster-placeholder-install-config
  namespace: cluster-placeholder
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: openshiftpartnerlabs.com
    metadata:
      name: cluster-placeholder
    controlPlane:
      name: master
      platform:
        azure:
          type: Standard_D8s_v5
          zones:
            - "1"
      replicas: 1
    compute:
      - name: worker
        replicas: 0
    networking:
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
      machineNetwork:
        - cidr: 10.0.0.0/16
      serviceNetwork:
        - 172.30.0.0/16
      networkType: OVNKubernetes
    platform:
      azure:
        baseDomainResourceGroupName: openshift-dns
        region: eastus
        cloudName: AzurePublicCloud
    publish: External
