- op: replace
  path: /metadata/name
  value: 264c5202-codvoqs
- op: replace
  path: /metadata/namespace
  value: 264c5202-codvoqs
- op: replace
  path: /spec/clusterName
  value: 264c5202-codvoqs
- op: replace
  path: /spec/platform/aws/region
  value: us-east-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: 264c5202-codvoqs-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: 264c5202-codvoqs-ssh-key
- op: replace
  path: /spec/provisioning/imageSetRef/name
  value: img4.21.14-x86-64-appsub
