- op: replace
  path: /metadata/name
  value: 10f25620-vscopeocpv
- op: replace
  path: /metadata/namespace
  value: 10f25620-vscopeocpv
- op: replace
  path: /spec/clusterName
  value: 10f25620-vscopeocpv
- op: replace
  path: /spec/platform/aws/region
  value: us-east-1
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: 10f25620-vscopeocpv-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: 10f25620-vscopeocpv-ssh-key
- op: replace
  path: /spec/provisioning/imageSetRef/name
  value: img4.21.14-x86-64-appsub
