- op: replace
  path: /metadata/name
  value: bf2f78dc-vantiqfips
- op: replace
  path: /metadata/namespace
  value: bf2f78dc-vantiqfips
- op: replace
  path: /spec/clusterName
  value: bf2f78dc-vantiqfips
- op: replace
  path: /spec/platform/aws/region
  value: us-west-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: bf2f78dc-vantiqfips-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: bf2f78dc-vantiqfips-ssh-key
- op: replace
  path: /spec/provisioning/imageSetRef/name
  value: img4.18.40-x86-64-appsub
