- op: replace
  path: /metadata/name
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /metadata/namespace
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /spec/clusterName
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /spec/platform/aws/region
  value: us-east-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: 9d0b02b8-zoomcc42-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: 9d0b02b8-zoomcc42-ssh-key
- op: replace
  path: /spec/provisioning/imageSetRef/name
  value: img4.21.20-x86-64-appsub
