- op: replace
  path: /metadata/name
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /metadata/namespace
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /spec/clusterName
  value: 9d0b02b8-zoomcc42
- op: replace
  path: /spec/clusterNamespace
  value: 9d0b02b8-zoomcc42
