apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  name: cluster-placeholder-sa-key
  namespace: cluster-placeholder
spec:
  forProvider:
    serviceAccountIdRef:
      name: cluster-placeholder-ocp-installer
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: gcp-credentials-raw
    namespace: cluster-placeholder
