apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: cluster-placeholder-ocp-installer
  namespace: cluster-placeholder
spec:
  forProvider:
    displayName: OpenShift Installer
    description: Service account for OpenShift 4.x installation
  providerConfigRef:
    name: default
