- op: replace
  path: /metadata/name
  value: 423d216c-vistergy
- op: replace
  path: /metadata/namespace
  value: 423d216c-vistergy
- op: replace
  path: /spec/clusterName
  value: 423d216c-vistergy
- op: replace
  path: /spec/platform/aws/region
  value: us-east-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: 423d216c-vistergy-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: 423d216c-vistergy-ssh-key
- op: replace
  path: /spec/provisioning/imageSetRef/name
  value: img4.18.40-x86-64-appsub
